### ISSUE TITLE
ffmpeg fails to run custom build command

### ISSUE THREAD

**Issue by Sanel-Trnka** [0Ky/screenclip#2]
Hi, while trying to run your project I get following error:

error: failed to run custom build command for `ffmpeg-sys-next v6.0.1`

Caused by:

  process didn't exit successfully: `C:\Projekte\Screenclip\src-tauri\target\debug\build\ffmpeg-sys-next-7a328b218e4e81a8\build-script-build` (exit code: 101)

Is it a known error you have been through as well? I followed the instructions to set up ffmpeg using the gnu toolchain.

Thanks for helping.

**Comment by 0Ky** [comment]
Please follow the [build instruction](https://github.com/0Ky/screenclip#-build-instructions) carefully. You must be in the `MSYS2` environment when building the application, be sure to follow the FFmpeg build instructions for the [GNU toolchain](https://github.com/zmwangx/rust-ffmpeg/wiki/Notes-on-building#gnu-toolchain) and install required packages in MinGW64.

If you still get the error message, can you post the entirety of the message, it should indicate what caused it to fail.

**Comment by 0Ky** [comment]
@Sanel-Trnka Okay, it seems you might have linked Rust from MinGW64 with the command `export PATH="/c/Users/$USER/.cargo/bin:$PATH"`. When you do this, the Rust compiler (rustc) probably recognizes the host as `x86_64-pc-windows-msvc`.

To resolve this, install Rust through MSYS2's package manager by running `pacman -S mingw-w64-x86_64-rust`. This will set the Rust compiler to recognize the host as `x86_64-pc-windows-gnu`, which should help you compile `ffmpeg-sys-next v6.0.1` without any hitches.

**Comment by Sanel-Trnka** [comment]
@0Ky Thanks for the hint with installing Rust through the pm. I think it was because I didn't use `MSYS2`. Now that error doen't occur anymore, but now another problem appeared. I had to install `Node.js` in the `MSYS2` environment, so I used `pacman -S mingw-w64-x86_64-nodejs`. It installs `Node.js` with version `v.18.17.1` and while running `npm run tauri dev`, following error occurs:

`$ npm run tauri dev

> screenclip-app@0.0.0 tauri
> env RUST_BACKTRACE=full tauri dev

thread '<unnamed>' panicked at 'Must load N-API bindings', C:\Users\runneradmin\.cargo\registry\src\
index.crates.io-6f17d22bba15001f\napi-sys-2.2.3\src\functions.rs:7:3
stack backtrace:
   0:     0x7ffd062dae61 - napi_register_module_v1
   1:     0x7ffd05d34b5b - bz_internal_error
   2:     0x7ffd062b6fd0 - napi_register_module_v1
   3:     0x7ffd062df64b - napi_register_module_v1
   4:     0x7ffd062df24e - napi_register_module_v1
   5:     0x7ffd062dee20 - napi_register_module_v1
   6:     0x7ffd062dff13 - napi_register_module_v1
   7:     0x7ffd062dfc73 - napi_register_module_v1
   8:     0x7ffd062dfbf9 - napi_register_module_v1
   9:     0x7ffd062dfbe4 - napi_register_module_v1
  10:     0x7ffd0688a455 - napi_register_module_v1
  11:     0x7ffd060826be - napi_register_module_v1
  12:     0x7ffd06082679 - napi_register_module_v1
  13:     0x7ffd0669a898 - napi_register_module_v1
  14:     0x7ffd0607ec48 - napi_register_module_v1
  15:     0x7ffd0607ac56 - napi_register_module_v1
  16:     0x7ffcfb88ed32 - napi_queue_async_work
  17:     0x7ffcfb8914d6 - node_module_register
  18:     0x7ffcfb8527e4 - ZN4node11IsolateData16CreatePropertiesEv
  19:     0x7ffcfb89030f - node_module_register
  20:     0x7ffcfbb49f6f - ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4Nam
eEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7Bool
eanEEEE
  21:     0x7ffcfbb4ab05 - ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4Nam
eEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7Bool
eanEEEE
  22:     0x7ffcfd26f57d - ZTv0_n24_N2v88internal8OFStreamD1Ev
  23:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  24:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  25:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  26:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  27:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  28:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  29:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  30:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  31:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  32:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  33:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  34:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  35:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  36:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  37:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  38:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  39:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  40:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  41:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  42:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  43:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  44:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  45:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  46:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  47:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  48:     0x7ffcfd1f2e90 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  49:     0x7ffcfd1f149c - ZTv0_n24_N2v88internal8OFStreamD1Ev
  50:     0x7ffcfd1f1097 - ZTv0_n24_N2v88internal8OFStreamD1Ev
  51:     0x7ffcfbc275b9 - ZN2v88internal9Execution8CallWasmEPNS0_7IsolateENS0_6HandleINS0_4CodeEEEy
NS4_INS0_6ObjectEEEy
  52:     0x7ffcfbc28517 - ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_
iPS6_
  53:     0x7ffcfbb11d98 - ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_
  54:     0x7ffcfb92f008 - ZN4node12OnFatalErrorEPKcS1_
  55:     0x7ffcfb884c38 - napi_define_class
  56:     0x7ffcfb8860b6 - ZN4node4StopEPNS_11EnvironmentENS_9StopFlags5FlagsE
  57:     0x7ffcfb816db6 - ZN4node15LoadEnvironmentEPNS_11EnvironmentESt8functionIFN2v810MaybeLocalI
NS3_5ValueEEERKNS_26StartExecutionCallbackInfoEEE
  58:     0x7ffcfb90452b - ZN4node12OnFatalErrorEPKcS1_
  59:     0x7ffcfb9049bf - ZN4node12OnFatalErrorEPKcS1_
  60:     0x7ffcfb8857da - ZN4node20InitializationResultD0Ev
  61:     0x7ffcfb88963a - ZN4node5StartEiPPc
  62:     0x7ff7c6b41593 - <unknown>
  63:     0x7ff7c6b412f7 - <unknown>
  64:     0x7ff7c6b41406 - <unknown>
  65:     0x7ffdc039257d - BaseThreadInitThunk
  66:     0x7ffdc1bcaa68 - RtlUserThreadStart`

When I try to run the command on powershell on my local machine, it runs perfectly and I have access to the tray. Do I really need to run it through `MSYS2` or is it also okay if I use the powershell command line?

**Comment by 0Ky** [comment]
There may be an issue with NodeJS in the MinGW package repository. Try running `export PATH="/c/Program Files/nodejs/:$PATH"` or add it to the `.bashrc` file in your home directory, so you don't have to run that command each session.

Edit: The error originates from the `napi-sys` Rust crate, which interfaces with Node.js's N-API for building native addons. The MSYS2 version of Node.js doesn't seem to have Rust bindings for N-API.

> When I try to run the command on powershell on my local machine

I'm assuming you have used build instructions for the MSVC toolchain to run it in PowerShell, is that correct?
There is actually nothing stopping you from using PowerShell, you are not required to run it through MSYS2 environment, as long as you can build all the dependencies.

**Comment by Sanel-Trnka** [comment]
@0Ky Not really, I have used build instructions for the GNU toolchain, though it somehow works. But thanks for the help!
